### PR TITLE
Some patches

### PR DESCRIPTION
**Pull request by gyurco**
- Interlaced modes
- sdram controller/cache fix
- SRAM support for some games
- option to turn on/off FIFO throttiling
- some cleanups
- and some bugfixes in SHI and interrupts (hopefully without new bugs)

### CODE REVIEW

**Comment by gyurco** [comment]
Now changed the vdpr for the same amount of lines in odd and even frames. The VGA mode doesn't like different line numbers, my TV doesn't care, the two games using interlaced modes work.
Actually I've used vdpsim for the sprites part, but would be good to fix it for all :)

**Comment by gyurco** [comment]
A test ROM for double-resolution interlaced mode:

http://gendev.spritesmind.net/forum/viewtopic.php?f=2&t=2693&p=32226&hilit=interlace#p32226

**Comment by gyurco** [comment]
Just thought about it: for proper half line emulation, maybe enough to shift vsync to the half of the last line.

**Comment by harbaum** [comment]
Yes, i also think the main factor is that vsync needs to be n+1/2 lines long.

**Comment by harbaum** [comment]
I just made vdpsim save two subsequent frames with data from the interlaced test rom. I am surprised that they both look the same. They should be different ...

**Comment by harbaum** [comment]
I think we should ignore the scandoubler by now and make sure that the interlaced signal itself looks fine.

**Comment by gyurco** [comment]
For rendering, every Y coordinate should be adjusted by the FIELD, so they should differ at least in double resolution mode (when the LSM regs = 3). For non-double res, yes, they'll be identical. Did you test the ROM I linked with the two red stripes and green sprites?
When the n and n+1 lines were implemented, I didn't notice any difference on my TV, but VGA was broken, so went to a setup, where they were the same. Also checked BlastEm, it seems it also doesn't use  different vcounter setups for interlaced modes.
Unfortunately I don't have any old TVs to test any changes.

**Comment by gyurco** [comment]
Checked the new vdpsim, hard to tell by the first sight if they're not shifted by one line, however the scandoubled output is clearly shows the effect of a one line shift.

**Comment by harbaum** [comment]
They are the same as verified by diff.

But also the contents should be very different.  An interlaced image consists of two completely different images.

**Comment by gyurco** [comment]
Strange, maybe the FIELD signal resetted between the two runs?

**Comment by gyurco** [comment]
I watched what vdispim does closely, seems it renders 4 frames, and saves the first and the third one, so they're identical.

**Comment by harbaum** [comment]
Really? I'll have a look at that ...

**Comment by harbaum** [comment]
Uhm ... indeed. Fixed that and it now saves two different frames.

**Comment by harbaum** [comment]
I'll now add two more things:
a) measure the time between the end of vsync and the first hsync as this imho determines the vertical half line offset required for interlace
b) reassemble both frames into a single one. The result should look like a blastem screenshot from an interlaced mode

**Comment by gyurco** [comment]
Good!
For a correct TV-output, there is one other thing to consider:
PAL now consists of 313 lines, the other frame must be 312 to have 625 line screen
NTSC is 262 lines, so the other frame must be 263 to have 525 lines.

**Comment by harbaum** [comment]
I've played a little but with a half line offset and it seems that for two of my screens that's actually sufficient.

**Comment by gyurco** [comment]
Could you try it on a CRT TV?

**Comment by harbaum** [comment]
I don't own a CRT and don't know anyone who has ...

**Comment by gyurco** [comment]
There's somebody in the family who still has, Maybe I'll go to her with the MiST at Christmas :)

**Comment by harbaum** [comment]
Just bring 'daze before christmas' with you and you'll be fine.

**Comment by gyurco** [comment]
That would make a real Christmas mood, together with "Nightmare before Christmas" movie :)

**Comment by gyurco** [comment]
Just tried it, seems scandoubler also doesn't like this sync shift :(

**Comment by harbaum** [comment]
My Dell PC screen likes the scandoubled interlaced signal. It definitely looks great there.

**Comment by gyurco** [comment]
Seems my monitors are not that forgiving.
Meanwhile have good results with the new CPU.

**Comment by harbaum** [comment]
I am still fiddling with the interlace offset. You basically cannot do perfect half lines since the HV_HCNT counter runs with different speeds in fast h40 mode and it does not allow to meet the timing exactly.

Is there some documentation of the h40 timing somewhere? Currently we have 390 HCNT cycles at 1/8 CLK and 30 cycles at 1/10 clock resulting in those 3420 clock cycles per line. Is this correct?

**Pull request merged**
